#!/bin/bash

if [ $# -ne 2 ]
then  echo "$0 image iso"
      exit 1
fi

chk_read(){
    read tmp
    if [ -z $tmp ]
    then echo $1
    else
	echo $tmp
    fi
}

brName=br0
echo "Open vSwitch Bridge Name: (default: $brName)"
printf "=> "
brName=$(chk_read $BrName)
TAP=taptmp$$

sudo chmod 666 /dev/net/tun
sudo tunctl -u `whoami` -t $TAP
sudo ifconfig $TAP 0.0.0.0 up
sudo ovs-vsctl add-port $brName $TAP
sudo modprobe vhost_net
sudo chmod 666 /dev/vhost-net

echo "Installing KVM..., mem=1024M"

kvm \
-smp 1 \
-m 1024M \
-netdev tap,id=$TAP,ifname=$TAP,vhost=on,script=no \
-net nic,model=virtio,netdev=$TAP,vlan=0 \
-monitor unix:/tmp/MonSock-tmp-$$,server,nowait \
-drive file=$1,if=virtio \
--cdrom $2 &
