#!/bin/bash
sudo echo Need SU passwd: 
sudo ovs-vsctl add-br br0 2>/dev/null
sudo ovs-vsctl add-port br0 eth1
sudo ifconfig eth1 0
sudo ifconfig br0 192.168.0.15   netmask 255.255.255.0
sudo route add default gw 
